### ISSUE TITLE
Isn't populating albums lists with my picasa albums after I've entered my username

### ISSUE THREAD

**Issue by broodingjay** [mikhailkozlov/Picasa-Albums-For-WordPress#1]
(see title)

**Comment by mikhailkozlov** [comment]
Thanks for feedback. Will do some debugging right now. I'll keep you posted.

**Comment by mikhailkozlov** [comment]
Committed new code. Please try and let me know so we can close this issue.

**Comment by broodingjay** [comment]
Tried new version.  Still not working for me.   Just says "Loading" indefinitely.

**Comment by mikhailkozlov** [comment]
Stange. I have tried to load your public images and it worked on my local machine. I will deploy it on a server and 'll give it another test drive. 

Do you have Firebug installed? If you do, check out console tab and see what kind if errors it throws. let me know if you see any. Thanks.

**Comment by mikhailkozlov** [comment]
It looks like JS and CSS files were not loading because of bad path. I have fixed folder path, so CSS and JS are loading fine. Now plugin can be installed into folder with any name. Please get the latest and give it a try.

**Comment by broodingjay** [comment]
Tried the latest build and it works great!  Thank you.

**Comment by mikhailkozlov** [comment]
np. thanks for your time.
