### ISSUE TITLE
What do i need to type for picasa userna,e

### ISSUE THREAD

**Issue by kduleo** [mikhailkozlov/Picasa-Albums-For-WordPress#12]
Dear sir,
May i know what should i type for picasa username? I didnt work for me.

**Comment by mikhailkozlov** [comment]
Usually it is your picasa username which is the same as your gmail username. If you use picasa with google apps you have to type your full email address. Unfortunately I do not know of other ways you can access picasa, but I heard there're some other ways you can be a user. Hope it helps. Moving to Wiki
