### ISSUE TITLE
Clicking on image, not showing large image

### ISSUE THREAD

**Issue by Jamesebdonmuir** [mikhailkozlov/Picasa-Albums-For-WordPress#14]
Hi,
I have a set of galleries here:
http://www.ebdon-muir.co.uk/album/

When looking at individual galleries, clicking on an image it does not open in new window or tab to reveal a bigger image.  I seem to remember this was operating properly before.  Has there been any other issues?
Regards
James

**Comment by mikhailkozlov** [comment]
What version are you using?

**Comment by Jamesebdonmuir** [comment]
Wordpress 3.2.1
Picasa 1.0.5

**Comment by mikhailkozlov** [comment]
if you used github to get plugin, checkout branch v1.0.6 (or wait and I merge it to master), if not I'll push it to SVN soon (should be up now)

**Comment by Jamesebdonmuir** [comment]
Thanks, i will try this...do i just overwrite files currently there, or will i need to uninstall the current plugin?
Sorry, not a master of this yet!
Thanks again.

**Comment by Jamesebdonmuir** [comment]
NO, worries, i just deleted the old and installed the new, not too much hassle as not many pics at the moment! :-)
Thanks again!
Works great now!
