### ISSUE TITLE
Paging does not work for me

### ISSUE THREAD

**Issue by sabuty** [mikhailkozlov/Picasa-Albums-For-WordPress#2]
Just installed the Plugin without problems, published some (20) Albums and the first 10 show up fine, but paging does not work and leads to a 404.

http://wp.maikfox.de/album
http://wp.maikfox.de/album/page/2/

**Comment by mikhailkozlov** [comment]
Thanks for feedback. will take a look asap

**Comment by mikhailkozlov** [comment]
as a temporary solution you can try to add:
$newrules['(album)/page/?([0-9]{1,})/?$'] = 'index.php?post_type=$matches[1]&paged=$matches[1]';

after line 404 in plugin.php. 

I will make a commit once test a bit.

**Comment by sabuty** [comment]
As you can see, the 404 is gone. No errors now.

But the paging itself isn't working, it just displays the same (first) page.

**Comment by sabuty** [comment]
$newrules['(album)/page/?([0-9]{1,})/?$'] = 'index.php?post_type=$matches[1]&paged=$matches[2]';

Hehe, using a "2" for the paged parameter fixed it. Thx!

**Comment by mikhailkozlov** [comment]
great, added to latest commit. thanks
