### ISSUE TITLE
Problem Importing Albums

### ISSUE THREAD

**Issue by drawab** [mikhailkozlov/Picasa-Albums-For-WordPress#4]
Ever since i installed the plugin, have been trying to import albums but there seems to be no output.  Is there any settings issue that needs to be tweaked for it to work?

Thanks

**Comment by mikhailkozlov** [comment]
Usually just enter your picasa ID, scroll down, save. Page reloads. Click import. First time it may take a little long.

**Comment by savrip** [comment]
Version 3.0.4, When I try to import the albums same deal, just stays loading indefinitely.  I've seen this tool in action and it's exactly what I'm looking for.  I'll be patient and see what comes with future updates.

**Comment by mikhailkozlov** [comment]
Please try new version if you have worpress in subdirectory.

**Comment by savrip** [comment]
I think I may know what it's doing.  It's been running for an hour so far.  I've noticed that some of my albums now have thumbnail-sized images.  Is the script creating thumbnails in the album for the use of the plugin?  If so I just need to let it finish.  If not, I'm getting quite a mess in my albums.  I have 69 total I'm pulling from.

**Comment by savrip** [comment]
I removed all but one web album to troubleshoot and know that it's not working on hundreds of images.  I deactivated all plugins to avoid conflict there.  It is not creating thumbnails in the single album.  I'm not sure why that was happening to other albums that were all under sync.  Still the 'import albums' never finishes.  Sorry for the double post, but I wanted to state what I had done to try to figure it out.

**Comment by mikhailkozlov** [comment]
actually plugin does not create a single thumbnail. Number of albums (bellow 100) should not matter. All plugin does is puts data from picasa into your wordpress. I have 55 albums and it works fine.

**Comment by savrip** [comment]
Today's update fixed whatever issues I was having.  Very nice.  Thank you so much.  I look forward to seeing the whole album in action once I get the rest uploaded.

**Comment by mikhailkozlov** [comment]
i think it was subfoler issue. I will close this issue
