### ISSUE TITLE
Wordpress installed in subdirectory doesn't work

### ISSUE THREAD

**Issue by stephanvierkant** [mikhailkozlov/Picasa-Albums-For-WordPress#5]
The plugin (/wp-admin/options-general.php?page=picasa-albums) is loading 'http://www.domain.tld/wp-admin/admin-ajax.php?action=picasa_ajax_import&user=username', but my wordpress is installed in a subdirectory: 'domain.tld/wordpress/', so the url doesn't exist.

**Comment by stephanvierkant** [comment]
Update: I'm using Wordpress 3.0.4. and plugin version 1.0.3.

The problem is in line 26 of /wp-content/plugins/picasa-albums/admin/scripts.js:            $j.get('/wp-admin/admin-ajax.php?action=picasa_ajax_import',{'user':$j('input#username').val(),'password':$j("#gpassword").val()},function(){

That path is absolute, but must be relative. Just remove '/wp-admin/' does the job.

**Comment by mikhailkozlov** [comment]
Did new commit. thanks.
