### ISSUE TITLE
SimpleXMLElement::xpath() warning on line 690

### ISSUE THREAD

**Issue by stephanvierkant** [mikhailkozlov/Picasa-Albums-For-WordPress#6]
I got an error while importing some albums. 

Firebug says this: 

GET http://www.domain.nl/wordpress/wp-admin/admin-ajax.php?action=picasa_ajax_import&user=username:

-- begin answer ---
doing ajax...<br />
<b>Warning</b>:  SimpleXMLElement::xpath() [<a href='simplexmlelement.xpath'>simplexmlelement.xpath</a>]: Undefined namespace prefix in <b>/home/hosting/domains/domain.nl/public_html/wordpress/wp-content/plugins/picasa-albums/plugin.php</b> on line <b>690</b><br />
<br />
<b>Warning</b>:  SimpleXMLElement::xpath() [<a href='simplexmlelement.xpath'>simplexmlelement.xpath</a>]: xmlXPathEval: evaluation failed in <b>/home/hosting/domains/domain.nl/public_html/wordpress/wp-content/plugins/picasa-albums/plugin.php</b> on line <b>690</b><br />
<br />
<b>Warning</b>:  SimpleXMLElement::xpath() [<a href='simplexmlelement.xpath'>simplexmlelement.xpath</a>]: Undefined namespace prefix in <b>/home/hosting/domains/domain.nl/public_html/wordpress/wp-content/plugins/picasa-albums/plugin.php</b> on line <b>690</b><br />
<br />
<b>Warning</b>:  SimpleXMLElement::xpath() [<a href='simplexmlelement.xpath'>simplexmlelement.xpath</a>]: xmlXPathEval: evaluation failed in <b>/home/hosting/domains/domain.nl/public_html/wordpress/wp-content/plugins/picasa-albums/plugin.php</b> on line <b>690</b><br />
new album [number] auth post id:219<br />new album [number] auth post id:220<br />

--- end answer ---

**Comment by mikhailkozlov** [comment]
i have added IF to check if path exists in v 1.0.4, hope it helps. Please let me know if it does. Thanks.
