### ISSUE TITLE
Importing Albums leads to all previous Albums being reset and unpublished

### ISSUE THREAD

**Issue by sabuty** [mikhailkozlov/Picasa-Albums-For-WordPress#7]
Title says it all... Importing Albums leads to all previous Albums being reset and unpublished. This is a pain, especially if you have entered (a lot of) Album descriptions, as they are also gone afterwards.

"All existing albums will remain untouched." doesn't really tell the truth here ;)

**Comment by mikhailkozlov** [comment]
yes. this feature was overdone. Idea was to update title and dates. But it looks like it does not make much sense to do so. I'll remove update in next realize.

**Comment by mikhailkozlov** [comment]
Closed by 14397f82c5bfcc9cb7b12532103dbcbc84470b6b
