### ISSUE TITLE
[Picasa Albums] Can't import photos from an account with '.'

### ISSUE THREAD

**Issue by beshur** [mikhailkozlov/Picasa-Albums-For-WordPress#9]
Hello.

Just tried your plug-in.
But I have an account with a dot (tk.skify), it's OK for Google (he just joins parts, I can write t.k.s.k.i.f.y for e-mail and it is alright).

So when I enter my login tk.skify 'Import' button becomes deactivated.

**Comment by mikhailkozlov** [comment]
Once you enter your name you have to scroll down and save user name. Import button will become active. 

I do not check for email, as your username can be what ever you want.

Let me know if it still does not work.

**Comment by beshur** [comment]
Thanks, it helped :)
The problem was because I tested it on a localhost.

But still it works poor - when choose the album to be published, there is a circle rolling for very looong, and it doesn't publishes -(
